import os

import numpy as np
import pandas as pd

cwd = os.getcwd()

month_border = [0,31,59,90,120,151,181,212,243,273,304,334,365]
month_len = [31,28,31,30,31,30,31,31,30,31,30,31]
months_specie = np.repeat(np.arange(1, 13), month_len)

stars_under_review = [
    'HD101501',
    'HD10780',
#    'HD110897',
#    'HD115404A',
#    'HD116442',
#    'HD116443',
#    'HD131156A',
#    'HD131156B',
    'HD144579',
    'HD145675',
    'HD1461',
    'HD149661',
#    'HD157214',
#    'HD158633',
#    'HD185144',
#    'HD19373',
    'HD201092',
    'HD20630',
#    'HD208313',
    'HD22049',
    'HD26965',
#    'HD4614A',
    'HD4628',
    'HD55575',
    'HD69830',
#    'HD82885',
    'HD99492']

HARPN_standards = ['HD4628','HD166620','HD122064','HD127334','HD144579','HD151288','HD10476']

NEID_standards = ['HD4628','HD9407','HD10700','HD127334','HD185144','HD211354',
                  'HD179957','HD116442','HD95735','HD166620','HD86728','HD68017',
                  'HD51419']

YARARA = pd.read_csv(cwd+'/TACS_Material/THE_YARARA.csv',index_col=0)

NEID_Gupta_25 = pd.read_csv(cwd+'/TACS_Material/THE_NEID.csv',index_col=0)
catalog_NEID = NEID_Gupta_25.loc[NEID_Gupta_25['Rank_NEID']>0]
NEID_Gupta_25 = NEID_Gupta_25.loc[NEID_Gupta_25['nobs_NEID']!=0]
catalog_YARARA = YARARA.loc[YARARA['nobs_DB']!=0]

catalog_2ES = pd.read_csv(cwd+'/TACS_Material/THE_2ES_TCS_tool.csv',index_col=0)
catalog_2ES  = catalog_2ES.loc[catalog_2ES['Rank_2ES']>0]

catalog_GR8 = pd.read_csv(cwd+'/TACS_Material/THE_Master_table_v2.0.csv',index_col=0)

cutoff_presurvey_old = {
    'teff<':6000,
    'logg>':4.2,
    'vsini<':5,
    'feh>':-0.4,
    'ruwe_GAIA<':1.2,
    'multi_peak_GAIA<':1,
    'sky_contam_VIZIER<':0.1,
    'rv_trend_kms_DACE<':0.1,
    'OBTP_type<':1.5,
    'eff_nights_1.75>':180,
    'season_length_1.75>':240,
    'HJ<':0.5,
    'BDW<':0.5,
    'logRHK<':-4.7,
    'gmag<':7.5,
    'HWO>':-1,
    'PLATO>':-1,
    'under_review>':-1,
    }

cutoff_RVopti = {
    'teff<':6000,
    'teff>':4000,
    'sig_rv_arve_phot+osc_texp15<':0.25,
    'OBTP_type<':1.5,
    'SB2<':0.5,
    'season_length_1.75>':240,
    'eff_nights_1.75>':180,
    'MHN<':1,
    'sky_contam_VIZIER<':0.01,
    'SB_composite<':0.5,
    'ruwe_GAIA<':1.2,
    'logRHK<':-4.7,
    'vsini<':5,
#    'feh>':-1.0,
    'multi_peak_GAIA<':1,
    'rv_trend_kms_DACE<':0.1,
    'prot>':10,
    'vmag<':7.3,
    'distance<':30,
    'HWO>':-1,
    'PLATO>':-1,
    'under_review>':-1,
    }

cutoff_megan = {
    'teff<':5927,
    'teff>':5627,
    'logg>':4.2,
    'OBTP_type<':1.5,
    'SB2<':1,
    'eff_nights_1.75>':180,
    'season_length_1.75>':240,
    'sky_contam_VIZIER<':0.1,
    'SB_composite<':0.5,
#    'vsini<':12,
#    'ruwe_GAIA<':10,
    'logRHK<':0,
#    'feh>':-1.0,
    'MHN>':-1,
    'gmag<':7.2,
    'distance<':50,
    'prot>':0,
    'HWO>':-1,
    'PLATO>':-1,
    'under_review>':-1,
    }

cutoff_megan_old = {
    'bp_rp<':0.87,
    'bp_rp>':0.77,
    'eff_nights_1.75>':180,
    'season_length_1.75>':240,
    'vsini<':5,
    'sky_contam_VIZIER<':0.1,
    'OBTP_type<':1.5,
    'sig_rv_arve_phot+osc_texp20<':0.30,
    'gmag<':7.5,
    }

cutoff_minimal = {
    'teff<':6050,
    'logg>':4.15,
    'vsini<':6,
    'sky_contam_VIZIER<':0.1,
    'OBTP_type<':1.5,
    'HJ<':0.5,
    'BDW<':0.5,
    'gmag<':7.5,
    'logRHK>':-6.1,
    'under_review>':-1,
    }

cutoff_tim = {
    'NIGHTS>':240,
    'Teff_phot<':6000,
    'Teff_spec<':6000,
    'Fe/H_spec>':-0.4,
    'parallax>':25,
    'log_ruwe<':np.round(np.log10(1.2),3),
    'vsini_spec<':3,
    'logRHK<':-4.8,
    'logg>':2.0,
    'gmag<':7,
    }

cutoff_jean = {
    'eff_nights_1.5>':160,
    'Teff_gspphot<':6000,
    'Teff_gspphot>':4500,
    'Fe/H>':-2.0,
    'parallax>':0,
    'log_ruwe<':np.round(np.log10(1.2),3),
    'vsini<':6,
    'logRHK<':-4.5,
    'logg_gspphot>':4,
    'gmag<':7,
    }

cutoff_sam = {
    'NIGHTS>':210,
    'Teff_phot<':5900,
    'Teff_phot>':4500,
    'Fe/H>':-2.0,
    'parallax>':0,
    'log_ruwe>':-2,
    'vsini<':50,
    'logRHK<':-4.0,
    'logg>':0.0,
    'gmag<':7.2,
}

cutoff_sam2 = {
    'NIGHTS>':240,
    'Teff_phot<':5900,
    'Teff_phot>':4500,
    'Fe/H>':-2.0,
    'parallax>':0,
    'log_ruwe>':0.041,
    'vsini<':10,
    'logRHK<':-4.0,
    'logg>':4.0,
    'gmag<':7.2,
}

cutoff_mick = {
    'eff_nights_1.5>':170,
    'teff_mean<':5900,
    'Fe/H>':-0.6,
    'parallax>':0,
    'log_ruwe<':np.round(np.log10(1.2),3),
    'vsini<':5,
    'logRHK<':-4.6,
    'logg>':4.2,
    'vmag<':7.3,
    'HZ_mp_min_osc+gr_texp15<':10,
}

cutoff_william1 = {
    'eff_nights_1.5>':180,
    'Teff_phot<':5980,
    'Teff_phot>':3865,
    'Teff_spec<':5980,
    'Teff_spec>':3865,
    'gmag<':6,
    }

cutoff_william2 = {
    'Teff_phot<':5980,
    'Teff_phot>':3865,
    'Teff_spec<':5980,
    'Teff_spec>':3865,
    'eff_nights_1.5>':180,
    'NIGHTS>':240,
    'Fe/H_spec>':-0.5,
    'parallax>':0,
    'log_ruwe<':np.round(np.log10(1.5),3),
    'logRHK<':-4.6,
    'logg>':0,
    'vsini_spec<':5,
    'gmag<':6.5,
    }

cutoff_stefano = {
 'dec_j2000>':-20,
 'teff_mean<':6000,
 'logg>':4.0,
 'vsini<':5,
 'Fe/H>':-0.4,
 'log_ruwe<':np.round(np.log10(1.2),3),
 'eff_nights_1.5>':160,
 'NIGHTS>':240,
 'HZ_period_inf>':250,
 'gmag<':7.5,
 'HZ_mp_min_osc+gr_texp15>':0.0,
 }




master_columns = ['PRIMARY',
    'GAIA',
    'HD',
    'HIP',
    'GJ',
    'TIC',
    'KIC',
    'CSTL',
    'WDS',
    'SPTP',
    'OBTP',
    'teff',
#    'teff_err',
    'logg',
    'logg_lerr',
    'logg_uerr',
    'feh',
#    'feh_err',
    'Ms',
    'Ms_lerr',
    'Ms_uerr',
    'Rs',
#    'Rs_err',
    'Ls',
#    'Ls_err',
    'HZ_period_inf',
    'HZ_period_sup',
    'HZ_amp_inf',
    'HZ_amp_sup',
    'logRHK',
    'vsini',
    'prot',
    'pmag',
    'vmag',
    'texp',
    'snr_420_texp15',
    'snr_550_texp15',
    'sig_rv_phot_texp15',
    'nb_subexp',
    'texp_snr_250',
    'snr_C22_texp15',
    'ra_j2000',
    'dec_j2000',
    'parallax',
    'distance',
    'pmra',
    'pmdec',
    'gmag',
    'bp_rp',
    'bmag',
    'radial_velocity',
    'season_length_1.5',
    'eff_nights_1.5',
    'eff_airmass_mean_1.5',
    'eff_seeing_1.5',
    'tyr_rise_1.5',
    'tyr_set_1.5',
    'season_length_1.75',
    'eff_nights_1.75',
    'eff_airmass_mean_1.75',
    'eff_seeing_1.75',
    'tyr_rise_1.75',
    'tyr_set_1.75',
    'SG_NGT_Jan',
    'SG_NGT_Feb',
    'SG_NGT_Mar',
    'SG_NGT_Apr',
    'SG_NGT_May',
    'SG_NGT_Jun',
    'SG_NGT_Jul',
    'SG_NGT_Aug',
    'SG_NGT_Sep',
    'SG_NGT_Oct',
    'SG_NGT_Nov',
    'SG_NGT_Dec',
    'nobs_NEID',
    'nobs_DB',
    'ruwe_GAIA',
    'logruwe_GAIA',
    'multi_peak_GAIA',
    'sky_contam_VIZIER',
    'rv_trend_kms_DACE',
    'SB2',
    'SB_composite',
    'OBTP_type',
    'HZ_detection_2ES',
    'Rank_2ES',
    'Rank_NEID',
    'Rank_THE',
    'HWO',
    'PLATO',
    'TESS_CVZ',
    'KEPLER',
    'MHS',
    'MHN',
    'HJ',
    'BDW',
    'GZ',
    'NEP',
    'SE',
    'TRNS',
    'TESS_candidates',
    'TOI',
    'TESS',
    'sig_rv_arve_osc_texp0',
    'sig_rv_arve_osc+gr_texp0',
    'sig_rv_gp_osc_texp0',
    'sig_rv_gp_osc+gr_texp0',
    'sig_rv_arve_phot+osc_texp0',
    'sig_rv_arve_phot+osc+gr_texp0',
    'sig_rv_gp_phot+osc_texp0',
    'sig_rv_gp_phot+osc+gr_texp0',
    'sig_rv_arve_osc_texp1',
    'sig_rv_arve_osc+gr_texp1',
    'sig_rv_gp_osc_texp1',
    'sig_rv_gp_osc+gr_texp1',
    'sig_rv_arve_phot+osc_texp1',
    'sig_rv_arve_phot+osc+gr_texp1',
    'sig_rv_gp_phot+osc_texp1',
    'sig_rv_gp_phot+osc+gr_texp1',
    'sig_rv_arve_osc_texp2',
    'sig_rv_arve_osc+gr_texp2',
    'sig_rv_gp_osc_texp2',
    'sig_rv_gp_osc+gr_texp2',
    'sig_rv_arve_phot+osc_texp2',
    'sig_rv_arve_phot+osc+gr_texp2',
    'sig_rv_gp_phot+osc_texp2',
    'sig_rv_gp_phot+osc+gr_texp2',
    'sig_rv_arve_osc_texp3',
    'sig_rv_arve_osc+gr_texp3',
    'sig_rv_gp_osc_texp3',
    'sig_rv_gp_osc+gr_texp3',
    'sig_rv_arve_phot+osc_texp3',
    'sig_rv_arve_phot+osc+gr_texp3',
    'sig_rv_gp_phot+osc_texp3',
    'sig_rv_gp_phot+osc+gr_texp3',
    'sig_rv_arve_osc_texp4',
    'sig_rv_arve_osc+gr_texp4',
    'sig_rv_gp_osc_texp4',
    'sig_rv_gp_osc+gr_texp4',
    'sig_rv_arve_phot+osc_texp4',
    'sig_rv_arve_phot+osc+gr_texp4',
    'sig_rv_gp_phot+osc_texp4',
    'sig_rv_gp_phot+osc+gr_texp4',
    'sig_rv_arve_osc_texp5',
    'sig_rv_arve_osc+gr_texp5',
    'sig_rv_gp_osc_texp5',
    'sig_rv_gp_osc+gr_texp5',
    'sig_rv_arve_phot+osc_texp5',
    'sig_rv_arve_phot+osc+gr_texp5',
    'sig_rv_gp_phot+osc_texp5',
    'sig_rv_gp_phot+osc+gr_texp5',
    'sig_rv_arve_osc_texp6',
    'sig_rv_arve_osc+gr_texp6',
    'sig_rv_gp_osc_texp6',
    'sig_rv_gp_osc+gr_texp6',
    'sig_rv_arve_phot+osc_texp6',
    'sig_rv_arve_phot+osc+gr_texp6',
    'sig_rv_gp_phot+osc_texp6',
    'sig_rv_gp_phot+osc+gr_texp6',
    'sig_rv_arve_osc_texp7',
    'sig_rv_arve_osc+gr_texp7',
    'sig_rv_gp_osc_texp7',
    'sig_rv_gp_osc+gr_texp7',
    'sig_rv_arve_phot+osc_texp7',
    'sig_rv_arve_phot+osc+gr_texp7',
    'sig_rv_gp_phot+osc_texp7',
    'sig_rv_gp_phot+osc+gr_texp7',
    'sig_rv_arve_osc_texp8',
    'sig_rv_arve_osc+gr_texp8',
    'sig_rv_gp_osc_texp8',
    'sig_rv_gp_osc+gr_texp8',
    'sig_rv_arve_phot+osc_texp8',
    'sig_rv_arve_phot+osc+gr_texp8',
    'sig_rv_gp_phot+osc_texp8',
    'sig_rv_gp_phot+osc+gr_texp8',
    'sig_rv_arve_osc_texp9',
    'sig_rv_arve_osc+gr_texp9',
    'sig_rv_gp_osc_texp9',
    'sig_rv_gp_osc+gr_texp9',
    'sig_rv_arve_phot+osc_texp9',
    'sig_rv_arve_phot+osc+gr_texp9',
    'sig_rv_gp_phot+osc_texp9',
    'sig_rv_gp_phot+osc+gr_texp9',
    'sig_rv_arve_osc_texp10',
    'sig_rv_arve_osc+gr_texp10',
    'sig_rv_gp_osc_texp10',
    'sig_rv_gp_osc+gr_texp10',
    'sig_rv_arve_phot+osc_texp10',
    'sig_rv_arve_phot+osc+gr_texp10',
    'sig_rv_gp_phot+osc_texp10',
    'sig_rv_gp_phot+osc+gr_texp10',
    'sig_rv_arve_osc_texp11',
    'sig_rv_arve_osc+gr_texp11',
    'sig_rv_gp_osc_texp11',
    'sig_rv_gp_osc+gr_texp11',
    'sig_rv_arve_phot+osc_texp11',
    'sig_rv_arve_phot+osc+gr_texp11',
    'sig_rv_gp_phot+osc_texp11',
    'sig_rv_gp_phot+osc+gr_texp11',
    'sig_rv_arve_osc_texp12',
    'sig_rv_arve_osc+gr_texp12',
    'sig_rv_gp_osc_texp12',
    'sig_rv_gp_osc+gr_texp12',
    'sig_rv_arve_phot+osc_texp12',
    'sig_rv_arve_phot+osc+gr_texp12',
    'sig_rv_gp_phot+osc_texp12',
    'sig_rv_gp_phot+osc+gr_texp12',
    'sig_rv_arve_osc_texp13',
    'sig_rv_arve_osc+gr_texp13',
    'sig_rv_gp_osc_texp13',
    'sig_rv_gp_osc+gr_texp13',
    'sig_rv_arve_phot+osc_texp13',
    'sig_rv_arve_phot+osc+gr_texp13',
    'sig_rv_gp_phot+osc_texp13',
    'sig_rv_gp_phot+osc+gr_texp13',
    'sig_rv_arve_osc_texp14',
    'sig_rv_arve_osc+gr_texp14',
    'sig_rv_gp_osc_texp14',
    'sig_rv_gp_osc+gr_texp14',
    'sig_rv_arve_phot+osc_texp14',
    'sig_rv_arve_phot+osc+gr_texp14',
    'sig_rv_gp_phot+osc_texp14',
    'sig_rv_gp_phot+osc+gr_texp14',
    'sig_rv_arve_osc_texp15',
    'sig_rv_arve_osc+gr_texp15',
    'sig_rv_gp_osc_texp15',
    'sig_rv_gp_osc+gr_texp15',
    'sig_rv_arve_phot+osc_texp15',
    'sig_rv_arve_phot+osc+gr_texp15',
    'sig_rv_gp_phot+osc_texp15',
    'sig_rv_gp_phot+osc+gr_texp15',
    'sig_rv_arve_osc_texp16',
    'sig_rv_arve_osc+gr_texp16',
    'sig_rv_gp_osc_texp16',
    'sig_rv_gp_osc+gr_texp16',
    'sig_rv_arve_phot+osc_texp16',
    'sig_rv_arve_phot+osc+gr_texp16',
    'sig_rv_gp_phot+osc_texp16',
    'sig_rv_gp_phot+osc+gr_texp16',
    'sig_rv_arve_osc_texp17',
    'sig_rv_arve_osc+gr_texp17',
    'sig_rv_gp_osc_texp17',
    'sig_rv_gp_osc+gr_texp17',
    'sig_rv_arve_phot+osc_texp17',
    'sig_rv_arve_phot+osc+gr_texp17',
    'sig_rv_gp_phot+osc_texp17',
    'sig_rv_gp_phot+osc+gr_texp17',
    'sig_rv_arve_osc_texp18',
    'sig_rv_arve_osc+gr_texp18',
    'sig_rv_gp_osc_texp18',
    'sig_rv_gp_osc+gr_texp18',
    'sig_rv_arve_phot+osc_texp18',
    'sig_rv_arve_phot+osc+gr_texp18',
    'sig_rv_gp_phot+osc_texp18',
    'sig_rv_gp_phot+osc+gr_texp18',
    'sig_rv_arve_osc_texp19',
    'sig_rv_arve_osc+gr_texp19',
    'sig_rv_gp_osc_texp19',
    'sig_rv_gp_osc+gr_texp19',
    'sig_rv_arve_phot+osc_texp19',
    'sig_rv_arve_phot+osc+gr_texp19',
    'sig_rv_gp_phot+osc_texp19',
    'sig_rv_gp_phot+osc+gr_texp19',
    'sig_rv_arve_osc_texp20',
    'sig_rv_arve_osc+gr_texp20',
    'sig_rv_gp_osc_texp20',
    'sig_rv_gp_osc+gr_texp20',
    'sig_rv_arve_phot+osc_texp20',
    'sig_rv_arve_phot+osc+gr_texp20',
    'sig_rv_gp_phot+osc_texp20',
    'sig_rv_gp_phot+osc+gr_texp20',
    'sig_rv_arve_osc_texp21',
    'sig_rv_arve_osc+gr_texp21',
    'sig_rv_gp_osc_texp21',
    'sig_rv_gp_osc+gr_texp21',
    'sig_rv_arve_phot+osc_texp21',
    'sig_rv_arve_phot+osc+gr_texp21',
    'sig_rv_gp_phot+osc_texp21',
    'sig_rv_gp_phot+osc+gr_texp21',
    'sig_rv_arve_osc_texp22',
    'sig_rv_arve_osc+gr_texp22',
    'sig_rv_gp_osc_texp22',
    'sig_rv_gp_osc+gr_texp22',
    'sig_rv_arve_phot+osc_texp22',
    'sig_rv_arve_phot+osc+gr_texp22',
    'sig_rv_gp_phot+osc_texp22',
    'sig_rv_gp_phot+osc+gr_texp22',
    'sig_rv_arve_osc_texp23',
    'sig_rv_arve_osc+gr_texp23',
    'sig_rv_gp_osc_texp23',
    'sig_rv_gp_osc+gr_texp23',
    'sig_rv_arve_phot+osc_texp23',
    'sig_rv_arve_phot+osc+gr_texp23',
    'sig_rv_gp_phot+osc_texp23',
    'sig_rv_gp_phot+osc+gr_texp23',
    'sig_rv_arve_osc_texp24',
    'sig_rv_arve_osc+gr_texp24',
    'sig_rv_gp_osc_texp24',
    'sig_rv_gp_osc+gr_texp24',
    'sig_rv_arve_phot+osc_texp24',
    'sig_rv_arve_phot+osc+gr_texp24',
    'sig_rv_gp_phot+osc_texp24',
    'sig_rv_gp_phot+osc+gr_texp24',
    'sig_rv_arve_osc_texp25',
    'sig_rv_arve_osc+gr_texp25',
    'sig_rv_gp_osc_texp25',
    'sig_rv_gp_osc+gr_texp25',
    'sig_rv_arve_phot+osc_texp25',
    'sig_rv_arve_phot+osc+gr_texp25',
    'sig_rv_gp_phot+osc_texp25',
    'sig_rv_gp_phot+osc+gr_texp25',
    'sig_rv_arve_osc_texp26',
    'sig_rv_arve_osc+gr_texp26',
    'sig_rv_gp_osc_texp26',
    'sig_rv_gp_osc+gr_texp26',
    'sig_rv_arve_phot+osc_texp26',
    'sig_rv_arve_phot+osc+gr_texp26',
    'sig_rv_gp_phot+osc_texp26',
    'sig_rv_gp_phot+osc+gr_texp26',
    'sig_rv_arve_osc_texp27',
    'sig_rv_arve_osc+gr_texp27',
    'sig_rv_gp_osc_texp27',
    'sig_rv_gp_osc+gr_texp27',
    'sig_rv_arve_phot+osc_texp27',
    'sig_rv_arve_phot+osc+gr_texp27',
    'sig_rv_gp_phot+osc_texp27',
    'sig_rv_gp_phot+osc+gr_texp27',
    'sig_rv_arve_osc_texp28',
    'sig_rv_arve_osc+gr_texp28',
    'sig_rv_gp_osc_texp28',
    'sig_rv_gp_osc+gr_texp28',
    'sig_rv_arve_phot+osc_texp28',
    'sig_rv_arve_phot+osc+gr_texp28',
    'sig_rv_gp_phot+osc_texp28',
    'sig_rv_gp_phot+osc+gr_texp28',
    'sig_rv_arve_osc_texp29',
    'sig_rv_arve_osc+gr_texp29',
    'sig_rv_gp_osc_texp29',
    'sig_rv_gp_osc+gr_texp29',
    'sig_rv_arve_phot+osc_texp29',
    'sig_rv_arve_phot+osc+gr_texp29',
    'sig_rv_gp_phot+osc_texp29',
    'sig_rv_gp_phot+osc+gr_texp29',
    'sig_rv_arve_osc_texp30',
    'sig_rv_arve_osc+gr_texp30',
    'sig_rv_gp_osc_texp30',
    'sig_rv_gp_osc+gr_texp30',
    'sig_rv_arve_phot+osc_texp30',
    'sig_rv_arve_phot+osc+gr_texp30',
    'sig_rv_gp_phot+osc_texp30',
    'sig_rv_gp_phot+osc+gr_texp30',
    'HZ_mp_min_osc_texp15',
    'HZ_mp_min_osc+gr_texp15']

