import os

import numpy as np
import pandas as pd
from pathlib import Path

BASE_DIR = str(Path(__file__).resolve().parent.parent)
MATERIAL_DIR = BASE_DIR + "/TACS_Material"
OUTPUT_DIR = BASE_DIR + "/TACS_OUTPUT"

month_border = [0,31,59,90,120,151,181,212,243,273,304,334,365]
month_len = [31,28,31,30,31,30,31,31,30,31,30,31]
months_specie = np.repeat(np.arange(1, 13), month_len)

vsini_calib = np.array([0.0, 1.8 ,  2.06,  2.69,  3.5 ,  4.39,  5.31,  6.26,  7.23,  8.2 ,
        9.18, 10.16, 11.15, 12.13, 13.12, 14.12, 15.11, 16.1 , 17.1 ,
       18.09, 19.09, 20.08, 21.08, 22.07, 23.07, 24.07, 25.06, 26.06,
       27.06, 28.06, 29.06, 30.05, 31.05, 32.05, 33.05, 34.05, 35.05,
       36.04, 37.04, 38.04, 39.04, 40.04])

RV_factor_calib = np.array([1.,  1.   , 0.971, 0.877, 0.767, 0.665, 0.577, 0.497, 0.433, 0.382,
       0.343, 0.306, 0.277, 0.252, 0.231, 0.213, 0.197, 0.183, 0.171,
       0.161, 0.151, 0.142, 0.134, 0.127, 0.121, 0.115, 0.109, 0.104,
       0.1  , 0.096, 0.092, 0.088, 0.085, 0.082, 0.079, 0.076, 0.074,
       0.071, 0.069, 0.067, 0.065, 0.063])


stars_to_observe = [
    'HD4614A',
    'HD10086',
    'HD24409',
    'HD26710',
    'HD37394',
    'HD101177A',
    'HD131156A',
    'HD139777',
    'HD140538A',
    'HD146946',
    'HD149806A',
    'HD177082',
    'HD179958',
    'HD211476',
    'HD217813',
    'HD218868',
]

stars_under_review = [
#    'HD101501',
    'HD10780',
#    'HD24496A',
#    'HD144579',
#    'HD145675',
    'HD1461',
    'HD149661',
    'HD201092',
    'HD26965',
    'HD4628',
    'HD55575',
    'HD69830',
    'HD37394',
    'HD47127',
    'HD50692',
#    'HD111395',
    'HD131156A',
    'HD190360',
    'HD199960',
    'HD217813',
]

THE_standards = ['HD146233','HD4628','HD186408','HD89269','HD158259']

HARPN_standards = ['HD4628','HD166620','HD122064','HD127334','HD144579','HD151288','HD10476']

NEID_standards = ['HD4628','HD9407','HD10700','HD127334','HD185144','HD211354',
                  'HD179957','HD116442','HD95735','HD166620','HD86728','HD68017',
                  'HD51419']

YARARA = pd.read_csv(MATERIAL_DIR+'/THE_YARARA.csv',index_col=0)

NEID_Gupta_25 = pd.read_csv(MATERIAL_DIR+'/THE_NEID.csv',index_col=0)
catalog_NEID = NEID_Gupta_25.loc[NEID_Gupta_25['Rank_NEID']>0]
NEID_Gupta_25 = NEID_Gupta_25.loc[NEID_Gupta_25['nobs_NEID']!=0]
catalog_YARARA = YARARA.loc[YARARA['nobs_DB']!=0]

catalog_2ES = pd.read_csv(MATERIAL_DIR+'/THE_2ES_TCS_tool.csv',index_col=0)
catalog_2ES  = catalog_2ES.loc[catalog_2ES['Rank_2ES']>0]

catalog_GR8 = pd.read_csv(MATERIAL_DIR+'/THE_Master_table_v2.0.csv',index_col=0)

cutoff_presurvey_old = {
    'teff<':6000,
    'logg>':4.2,
    'vsini<':5,
    'feh>':-0.4,
    'ruwe_GAIA<':1.2,
    'multi_peak_GAIA<':1,
    'sky_contam_VIZIER<':0.1,
    'rv_trend_kms_DACE<':0.1,
    'OBTP_type<':1.5,
    'eff_nights_1.75>':180,
    'season_length_1.75>':240,
    'HJ<':0.5,
    'BDW<':0.5,
    'logRHK<':-4.7,
    'gmag<':7.5,
    'HWO>':-1,
    'PLATO>':-1,
    'under_review>':-1,
    }

cutoff_RVopti = {
    'teff<':6000,
    'teff>':4000,
    'sig_rv_arve_phot+osc_texp15<':0.25,
    'OBTP_type<':1.5,
    'SB2<':0.5,
    'season_length_1.75>':240,
    'eff_nights_1.75>':180,
#    'MHN<':1,
    'MP_stability>':50,
    'sky_contam_VIZIER<':0.01,
    'SB_composite<':0.5,
    'logRHK<':-4.7,
    'vsini<':5,
    'ruwe_GAIA<':1.2,
#    'feh>':-1.0,
    'multi_peak_GAIA<':1,
    'rv_trend_kms_DACE<':0.1,
#    'prot>':10,
    'gmag<':7.0,#'gmag<':7.2,
#    'distance<':30,
    'HWO>':-1,
    'PLATO>':-1,
    'under_review>':-1,
    }

cutoff_megan = {
    'teff<':5927,
    'teff>':5627,
    'logg>':4.2,
    'OBTP_type<':1.5,
    'SB2<':1,
    'eff_nights_1.75>':180,
    'season_length_1.75>':240,
    'sky_contam_VIZIER<':0.01,
    'SB_composite<':0.5,
    'vsini<':7,
#    'ruwe_GAIA<':10,
    'logRHK<':-4.5,
#    'feh>':-1.0,
    'MP_stability>':-1,
    'gmag<':7.3,#'gmag<':7.3,
    'distance<':50,
    'prot>':0,
    'HWO>':-1,
    'PLATO>':-1,
    'under_review>':-1,
    }

cutoff_megan_old = {
    'bp_rp<':0.87,
    'bp_rp>':0.77,
    'eff_nights_1.75>':180,
    'season_length_1.75>':240,
    'vsini<':5,
    'sky_contam_VIZIER<':0.01,
    'OBTP_type<':1.5,
    'sig_rv_arve_phot+osc_texp20<':0.30,
    'gmag<':7.5,
    }

cutoff_wide_sample = {
    'teff<':6100,
    'teff>':3900,
    'logg>':4.15,
    'vsini<':7,
    'SB2<':1,
    'logRHK<':-4.5,
    'sky_contam_VIZIER<':0.01,
    'SB_composite<':0.5,
    'OBTP_type<':1.5,
    'eff_nights_1.75>':180,
    'season_length_1.75>':240,
    'gmag<':7.5,
    }

cutoff_wide_josh_paper = {
    'eff_nights_1.75>':160,
    'sky_contam_VIZIER<':0.01,
    'OBTP_type<':1.5,
    'SB2<':0.5,
    'teff<':6000,
    'logg>':4.15,
    'vsini<':5,
    'Ls>':0.1,
    'gmag<':8.0,
    'HWO>':-1,
    'PLATO>':-1,
    'under_review>':-1,
    }

#Based on THE papers

cutoff_wide_josh_new = {
    'eff_nights_1.75>':160,
    'sky_contam_VIZIER<':0.01,
    'OBTP_type<':1.5,
    'SB2<':0.5,
    'teff<':6000,
    'logg>':4.15,
    'vsini<':5,
    'Ls>':0.1,
    'season_length_1.75>':240,
    'logRHK<':-4.7,
    'logg&>':4.20,
    'gmag<':8.0,
    'HWO>':-1,
    'PLATO>':-1,
    }

cutoff_RVopti_paper = {
    'eff_nights_1.75>':160,
    'season_length_1.75>':240,
    'sky_contam_VIZIER<':0.01,
    'OBTP_type<':1.5,
    'SB2<':0.5,
    'teff<':6000,
    'logg>':4.2,
    'vsini<':5,
    'Ls>':0.1,
    'logRHK<':-4.7,
    'MP_stability>':50,
    'ruwe_GAIA<':1.2,
    'multi_peak_GAIA<':1,
    'rv_trend_kms_DACE<':0.1,
    'gmag<':7.0,#'gmag<':7.2,
    'HWO>':-1,
    'PLATO>':-1,
    'under_review>':-1,
    }

cutoff_tim = {
    'NIGHTS>':240,
    'Teff_phot<':6000,
    'Teff_spec<':6000,
    'Fe/H_spec>':-0.4,
    'parallax>':25,
    'log_ruwe<':np.round(np.log10(1.2),3),
    'vsini_spec<':3,
    'logRHK<':-4.8,
    'logg>':2.0,
    'gmag<':7,
    }

cutoff_jean = {
    'eff_nights_1.5>':160,
    'Teff_gspphot<':6000,
    'Teff_gspphot>':4500,
    'Fe/H>':-2.0,
    'parallax>':0,
    'log_ruwe<':np.round(np.log10(1.2),3),
    'vsini<':6,
    'logRHK<':-4.5,
    'logg_gspphot>':4,
    'gmag<':7,
    }

cutoff_sam = {
    'NIGHTS>':210,
    'Teff_phot<':5900,
    'Teff_phot>':4500,
    'Fe/H>':-2.0,
    'parallax>':0,
    'log_ruwe>':-2,
    'vsini<':50,
    'logRHK<':-4.0,
    'logg>':0.0,
    'gmag<':7.2,
}

cutoff_sam2 = {
    'NIGHTS>':240,
    'Teff_phot<':5900,
    'Teff_phot>':4500,
    'Fe/H>':-2.0,
    'parallax>':0,
    'log_ruwe>':0.041,
    'vsini<':10,
    'logRHK<':-4.0,
    'logg>':4.0,
    'gmag<':7.2,
}

cutoff_mick = {
    'eff_nights_1.5>':170,
    'teff_mean<':5900,
    'Fe/H>':-0.6,
    'parallax>':0,
    'log_ruwe<':np.round(np.log10(1.2),3),
    'vsini<':5,
    'logRHK<':-4.6,
    'logg>':4.2,
    'vmag<':7.3,
    'HZ_mp_min_osc+gr_texp15<':10,
}

cutoff_william1 = {
    'eff_nights_1.5>':180,
    'Teff_phot<':5980,
    'Teff_phot>':3865,
    'Teff_spec<':5980,
    'Teff_spec>':3865,
    'gmag<':6,
    }

cutoff_william2 = {
    'Teff_phot<':5980,
    'Teff_phot>':3865,
    'Teff_spec<':5980,
    'Teff_spec>':3865,
    'eff_nights_1.5>':180,
    'NIGHTS>':240,
    'Fe/H_spec>':-0.5,
    'parallax>':0,
    'log_ruwe<':np.round(np.log10(1.5),3),
    'logRHK<':-4.6,
    'logg>':0,
    'vsini_spec<':5,
    'gmag<':6.5,
    }

cutoff_stefano = {
 'dec_j2000>':-20,
 'teff_mean<':6000,
 'logg>':4.0,
 'vsini<':5,
 'Fe/H>':-0.4,
 'log_ruwe<':np.round(np.log10(1.2),3),
 'eff_nights_1.5>':160,
 'NIGHTS>':240,
 'HZ_period_inf>':250,
 'gmag<':7.5,
 'HZ_mp_min_osc+gr_texp15>':0.0,
 }




master_columns = ['PRIMARY',
    'GAIA',
    'HD',
    'HIP',
    'GJ',
    'TIC',
    'KIC',
    'CSTL',
    'WDS',
    'SPTP',
    'OBTP',
    'teff',
#    'teff_err',
    'logg',
    'logg_lerr',
    'logg_uerr',
    'feh',
#    'feh_err',
    'Ms',
    'Ms_lerr',
    'Ms_uerr',
    'Rs',
#    'Rs_err',
    'Ls',
#    'Ls_err',
    'HZ_period_inf',
    'HZ_period_sup',
    'HZ_amp_inf',
    'HZ_amp_sup',
    'logRHK',
    'vsini',
    'prot',
    'pmag',
    'vmag',
    'texp',
    'snr_420_texp15',
    'snr_550_texp15',
    'sig_rv_phot_texp15',
    'nb_subexp',
    'texp_snr_250',
    'snr_C22_texp15',
    'ra_j2000',
    'dec_j2000',
    'parallax',
    'distance',
    'pmra',
    'pmdec',
    'gmag',
    'bp_rp',
    'bmag',
    'radial_velocity',
    'season_length_1.5',
    'eff_nights_1.5',
    'eff_airmass_mean_1.5',
    'eff_seeing_1.5',
    'tyr_rise_1.5',
    'tyr_set_1.5',
    'season_length_1.75',
    'eff_nights_1.75',
    'eff_airmass_mean_1.75',
    'eff_seeing_1.75',
    'tyr_rise_1.75',
    'tyr_set_1.75',
    'SG_NGT_Jan',
    'SG_NGT_Feb',
    'SG_NGT_Mar',
    'SG_NGT_Apr',
    'SG_NGT_May',
    'SG_NGT_Jun',
    'SG_NGT_Jul',
    'SG_NGT_Aug',
    'SG_NGT_Sep',
    'SG_NGT_Oct',
    'SG_NGT_Nov',
    'SG_NGT_Dec',
    'nobs_NEID',
    'nobs_DB',
    'ruwe_GAIA',
    'logruwe_GAIA',
    'multi_peak_GAIA',
    'sky_contam_VIZIER',
    'rv_trend_kms_DACE',
    'SB2',
    'SB_composite',
    'OBTP_type',
    'HZ_detection_2ES',
    'Rank_2ES',
    'Rank_NEID',
    'Rank_THE',
    'HWO',
    'PLATO',
    'TESS_CVZ',
    'KEPLER',
    'MHS',
    'MHN',
    'HJ',
    'BDW',
    'GZ',
    'NEP',
    'SE',
    'TRNS',
    'TESS_candidates',
    'TOI',
    'TESS',
    'sig_rv_arve_osc_texp0',
    'sig_rv_arve_osc+gr_texp0',
    'sig_rv_gp_osc_texp0',
    'sig_rv_gp_osc+gr_texp0',
    'sig_rv_arve_phot+osc_texp0',
    'sig_rv_arve_phot+osc+gr_texp0',
    'sig_rv_gp_phot+osc_texp0',
    'sig_rv_gp_phot+osc+gr_texp0',
    'sig_rv_arve_osc_texp1',
    'sig_rv_arve_osc+gr_texp1',
    'sig_rv_gp_osc_texp1',
    'sig_rv_gp_osc+gr_texp1',
    'sig_rv_arve_phot+osc_texp1',
    'sig_rv_arve_phot+osc+gr_texp1',
    'sig_rv_gp_phot+osc_texp1',
    'sig_rv_gp_phot+osc+gr_texp1',
    'sig_rv_arve_osc_texp2',
    'sig_rv_arve_osc+gr_texp2',
    'sig_rv_gp_osc_texp2',
    'sig_rv_gp_osc+gr_texp2',
    'sig_rv_arve_phot+osc_texp2',
    'sig_rv_arve_phot+osc+gr_texp2',
    'sig_rv_gp_phot+osc_texp2',
    'sig_rv_gp_phot+osc+gr_texp2',
    'sig_rv_arve_osc_texp3',
    'sig_rv_arve_osc+gr_texp3',
    'sig_rv_gp_osc_texp3',
    'sig_rv_gp_osc+gr_texp3',
    'sig_rv_arve_phot+osc_texp3',
    'sig_rv_arve_phot+osc+gr_texp3',
    'sig_rv_gp_phot+osc_texp3',
    'sig_rv_gp_phot+osc+gr_texp3',
    'sig_rv_arve_osc_texp4',
    'sig_rv_arve_osc+gr_texp4',
    'sig_rv_gp_osc_texp4',
    'sig_rv_gp_osc+gr_texp4',
    'sig_rv_arve_phot+osc_texp4',
    'sig_rv_arve_phot+osc+gr_texp4',
    'sig_rv_gp_phot+osc_texp4',
    'sig_rv_gp_phot+osc+gr_texp4',
    'sig_rv_arve_osc_texp5',
    'sig_rv_arve_osc+gr_texp5',
    'sig_rv_gp_osc_texp5',
    'sig_rv_gp_osc+gr_texp5',
    'sig_rv_arve_phot+osc_texp5',
    'sig_rv_arve_phot+osc+gr_texp5',
    'sig_rv_gp_phot+osc_texp5',
    'sig_rv_gp_phot+osc+gr_texp5',
    'sig_rv_arve_osc_texp6',
    'sig_rv_arve_osc+gr_texp6',
    'sig_rv_gp_osc_texp6',
    'sig_rv_gp_osc+gr_texp6',
    'sig_rv_arve_phot+osc_texp6',
    'sig_rv_arve_phot+osc+gr_texp6',
    'sig_rv_gp_phot+osc_texp6',
    'sig_rv_gp_phot+osc+gr_texp6',
    'sig_rv_arve_osc_texp7',
    'sig_rv_arve_osc+gr_texp7',
    'sig_rv_gp_osc_texp7',
    'sig_rv_gp_osc+gr_texp7',
    'sig_rv_arve_phot+osc_texp7',
    'sig_rv_arve_phot+osc+gr_texp7',
    'sig_rv_gp_phot+osc_texp7',
    'sig_rv_gp_phot+osc+gr_texp7',
    'sig_rv_arve_osc_texp8',
    'sig_rv_arve_osc+gr_texp8',
    'sig_rv_gp_osc_texp8',
    'sig_rv_gp_osc+gr_texp8',
    'sig_rv_arve_phot+osc_texp8',
    'sig_rv_arve_phot+osc+gr_texp8',
    'sig_rv_gp_phot+osc_texp8',
    'sig_rv_gp_phot+osc+gr_texp8',
    'sig_rv_arve_osc_texp9',
    'sig_rv_arve_osc+gr_texp9',
    'sig_rv_gp_osc_texp9',
    'sig_rv_gp_osc+gr_texp9',
    'sig_rv_arve_phot+osc_texp9',
    'sig_rv_arve_phot+osc+gr_texp9',
    'sig_rv_gp_phot+osc_texp9',
    'sig_rv_gp_phot+osc+gr_texp9',
    'sig_rv_arve_osc_texp10',
    'sig_rv_arve_osc+gr_texp10',
    'sig_rv_gp_osc_texp10',
    'sig_rv_gp_osc+gr_texp10',
    'sig_rv_arve_phot+osc_texp10',
    'sig_rv_arve_phot+osc+gr_texp10',
    'sig_rv_gp_phot+osc_texp10',
    'sig_rv_gp_phot+osc+gr_texp10',
    'sig_rv_arve_osc_texp11',
    'sig_rv_arve_osc+gr_texp11',
    'sig_rv_gp_osc_texp11',
    'sig_rv_gp_osc+gr_texp11',
    'sig_rv_arve_phot+osc_texp11',
    'sig_rv_arve_phot+osc+gr_texp11',
    'sig_rv_gp_phot+osc_texp11',
    'sig_rv_gp_phot+osc+gr_texp11',
    'sig_rv_arve_osc_texp12',
    'sig_rv_arve_osc+gr_texp12',
    'sig_rv_gp_osc_texp12',
    'sig_rv_gp_osc+gr_texp12',
    'sig_rv_arve_phot+osc_texp12',
    'sig_rv_arve_phot+osc+gr_texp12',
    'sig_rv_gp_phot+osc_texp12',
    'sig_rv_gp_phot+osc+gr_texp12',
    'sig_rv_arve_osc_texp13',
    'sig_rv_arve_osc+gr_texp13',
    'sig_rv_gp_osc_texp13',
    'sig_rv_gp_osc+gr_texp13',
    'sig_rv_arve_phot+osc_texp13',
    'sig_rv_arve_phot+osc+gr_texp13',
    'sig_rv_gp_phot+osc_texp13',
    'sig_rv_gp_phot+osc+gr_texp13',
    'sig_rv_arve_osc_texp14',
    'sig_rv_arve_osc+gr_texp14',
    'sig_rv_gp_osc_texp14',
    'sig_rv_gp_osc+gr_texp14',
    'sig_rv_arve_phot+osc_texp14',
    'sig_rv_arve_phot+osc+gr_texp14',
    'sig_rv_gp_phot+osc_texp14',
    'sig_rv_gp_phot+osc+gr_texp14',
    'sig_rv_arve_osc_texp15',
    'sig_rv_arve_osc+gr_texp15',
    'sig_rv_gp_osc_texp15',
    'sig_rv_gp_osc+gr_texp15',
    'sig_rv_arve_phot+osc_texp15',
    'sig_rv_arve_phot+osc+gr_texp15',
    'sig_rv_gp_phot+osc_texp15',
    'sig_rv_gp_phot+osc+gr_texp15',
    'sig_rv_arve_osc_texp16',
    'sig_rv_arve_osc+gr_texp16',
    'sig_rv_gp_osc_texp16',
    'sig_rv_gp_osc+gr_texp16',
    'sig_rv_arve_phot+osc_texp16',
    'sig_rv_arve_phot+osc+gr_texp16',
    'sig_rv_gp_phot+osc_texp16',
    'sig_rv_gp_phot+osc+gr_texp16',
    'sig_rv_arve_osc_texp17',
    'sig_rv_arve_osc+gr_texp17',
    'sig_rv_gp_osc_texp17',
    'sig_rv_gp_osc+gr_texp17',
    'sig_rv_arve_phot+osc_texp17',
    'sig_rv_arve_phot+osc+gr_texp17',
    'sig_rv_gp_phot+osc_texp17',
    'sig_rv_gp_phot+osc+gr_texp17',
    'sig_rv_arve_osc_texp18',
    'sig_rv_arve_osc+gr_texp18',
    'sig_rv_gp_osc_texp18',
    'sig_rv_gp_osc+gr_texp18',
    'sig_rv_arve_phot+osc_texp18',
    'sig_rv_arve_phot+osc+gr_texp18',
    'sig_rv_gp_phot+osc_texp18',
    'sig_rv_gp_phot+osc+gr_texp18',
    'sig_rv_arve_osc_texp19',
    'sig_rv_arve_osc+gr_texp19',
    'sig_rv_gp_osc_texp19',
    'sig_rv_gp_osc+gr_texp19',
    'sig_rv_arve_phot+osc_texp19',
    'sig_rv_arve_phot+osc+gr_texp19',
    'sig_rv_gp_phot+osc_texp19',
    'sig_rv_gp_phot+osc+gr_texp19',
    'sig_rv_arve_osc_texp20',
    'sig_rv_arve_osc+gr_texp20',
    'sig_rv_gp_osc_texp20',
    'sig_rv_gp_osc+gr_texp20',
    'sig_rv_arve_phot+osc_texp20',
    'sig_rv_arve_phot+osc+gr_texp20',
    'sig_rv_gp_phot+osc_texp20',
    'sig_rv_gp_phot+osc+gr_texp20',
    'sig_rv_arve_osc_texp21',
    'sig_rv_arve_osc+gr_texp21',
    'sig_rv_gp_osc_texp21',
    'sig_rv_gp_osc+gr_texp21',
    'sig_rv_arve_phot+osc_texp21',
    'sig_rv_arve_phot+osc+gr_texp21',
    'sig_rv_gp_phot+osc_texp21',
    'sig_rv_gp_phot+osc+gr_texp21',
    'sig_rv_arve_osc_texp22',
    'sig_rv_arve_osc+gr_texp22',
    'sig_rv_gp_osc_texp22',
    'sig_rv_gp_osc+gr_texp22',
    'sig_rv_arve_phot+osc_texp22',
    'sig_rv_arve_phot+osc+gr_texp22',
    'sig_rv_gp_phot+osc_texp22',
    'sig_rv_gp_phot+osc+gr_texp22',
    'sig_rv_arve_osc_texp23',
    'sig_rv_arve_osc+gr_texp23',
    'sig_rv_gp_osc_texp23',
    'sig_rv_gp_osc+gr_texp23',
    'sig_rv_arve_phot+osc_texp23',
    'sig_rv_arve_phot+osc+gr_texp23',
    'sig_rv_gp_phot+osc_texp23',
    'sig_rv_gp_phot+osc+gr_texp23',
    'sig_rv_arve_osc_texp24',
    'sig_rv_arve_osc+gr_texp24',
    'sig_rv_gp_osc_texp24',
    'sig_rv_gp_osc+gr_texp24',
    'sig_rv_arve_phot+osc_texp24',
    'sig_rv_arve_phot+osc+gr_texp24',
    'sig_rv_gp_phot+osc_texp24',
    'sig_rv_gp_phot+osc+gr_texp24',
    'sig_rv_arve_osc_texp25',
    'sig_rv_arve_osc+gr_texp25',
    'sig_rv_gp_osc_texp25',
    'sig_rv_gp_osc+gr_texp25',
    'sig_rv_arve_phot+osc_texp25',
    'sig_rv_arve_phot+osc+gr_texp25',
    'sig_rv_gp_phot+osc_texp25',
    'sig_rv_gp_phot+osc+gr_texp25',
    'sig_rv_arve_osc_texp26',
    'sig_rv_arve_osc+gr_texp26',
    'sig_rv_gp_osc_texp26',
    'sig_rv_gp_osc+gr_texp26',
    'sig_rv_arve_phot+osc_texp26',
    'sig_rv_arve_phot+osc+gr_texp26',
    'sig_rv_gp_phot+osc_texp26',
    'sig_rv_gp_phot+osc+gr_texp26',
    'sig_rv_arve_osc_texp27',
    'sig_rv_arve_osc+gr_texp27',
    'sig_rv_gp_osc_texp27',
    'sig_rv_gp_osc+gr_texp27',
    'sig_rv_arve_phot+osc_texp27',
    'sig_rv_arve_phot+osc+gr_texp27',
    'sig_rv_gp_phot+osc_texp27',
    'sig_rv_gp_phot+osc+gr_texp27',
    'sig_rv_arve_osc_texp28',
    'sig_rv_arve_osc+gr_texp28',
    'sig_rv_gp_osc_texp28',
    'sig_rv_gp_osc+gr_texp28',
    'sig_rv_arve_phot+osc_texp28',
    'sig_rv_arve_phot+osc+gr_texp28',
    'sig_rv_gp_phot+osc_texp28',
    'sig_rv_gp_phot+osc+gr_texp28',
    'sig_rv_arve_osc_texp29',
    'sig_rv_arve_osc+gr_texp29',
    'sig_rv_gp_osc_texp29',
    'sig_rv_gp_osc+gr_texp29',
    'sig_rv_arve_phot+osc_texp29',
    'sig_rv_arve_phot+osc+gr_texp29',
    'sig_rv_gp_phot+osc_texp29',
    'sig_rv_gp_phot+osc+gr_texp29',
    'sig_rv_arve_osc_texp30',
    'sig_rv_arve_osc+gr_texp30',
    'sig_rv_gp_osc_texp30',
    'sig_rv_gp_osc+gr_texp30',
    'sig_rv_arve_phot+osc_texp30',
    'sig_rv_arve_phot+osc+gr_texp30',
    'sig_rv_gp_phot+osc_texp30',
    'sig_rv_gp_phot+osc+gr_texp30',
    'HZ_mp_min_osc_texp15',
    'HZ_mp_min_osc+gr_texp15']



journal = {
    '1.40':'• Creation of the journal',
    '1.41':'• Dynamic HZ score metric computed by the .compute_ranking() \n• Add of the minimal and critical exposure time',
    '1.42':'• Planetary systems bug fixed \n• MP stability value displayed',
    '1.43':'• Construction of a minimal cutoff wide sample as a backup pool',
    '1.44':'• HWO Tier A,B,C (1,2,3) From Harada+25 and != inequality in func_cutoff()',    
    '2.00':'• Clean install and relative paths for TCS variables and material',    
    '2.01':'• Fix minors bugs to run again TCS_presurvey.py',
    '2.02':'• Fix minors bugs (change RA from hours to deg) to SG calender',
   }
